[uwsgi]
project = the-cua-tui-service
chdir = /webapps/the-cua-tui-service
master = true
workers = 2
max-requests = 100000
idle = 3600
buffer-size = 8192
gevent = 2000
max-fd = 200000
module = manage
vacuum = true
cheap = true
callable = app
http-socket = 0.0.0.0:5005
chown-socket=root:root
uid = root
touch-reload = /tmp/the-cua-tui-service.touch
